### ISSUE TITLE
ValueError: Sample larger than population or is negative

### ISSUE THREAD

**Issue by tianyuntong1020** [DZhaoXd/DT-ST#4]
Hello, thank you for providing the code for this paper. I tried to replace the source model with another model.  When reading the data, a "ValueError: Sample larger than population or is negative" will appear when performing random.sample(self.label_to_file[class_idx], 1) in the cityscape_b file. Is the predicted probability of some categories from the source model is 0?

**Comment by DZhaoXd** [comment]
Hi, could you provide the full print log?  In cityscapes_b.py, if the predicted probability of a class is 0, it will not be sampled.

**Comment by tianyuntong1020** [comment]
Traceback (most recent call last):
------------------------city balance sample-----------------------------
  File "train_TCR_DTU.py", line 948, in <module>
    main()
  File "train_TCR_DTU.py", line 941, in main
    fea, cls = train(cfg, args.local_rank, args.distributed)
  File "train_TCR_DTU.py", line 414, in train
    for i, (tgt_input, y, names, tgt_trans_param, tgt_img_full, mix_label) in enumerate(tgt_train_loader):
  File "/home/tianyuntong/anaconda3/envs/dtst/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/tianyuntong/anaconda3/envs/dtst/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/tianyuntong/anaconda3/envs/dtst/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tianyuntong/anaconda3/envs/dtst/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tianyuntong/project/DT-ST-main/core/datasets/cityscapes_b.py", line 377, in __getitem__
    trans_image, mix_label = self.mixer.mix(trans_image, self.mix_classes, self.mix_p)
  File "/home/tianyuntong/project/DT-ST-main/core/datasets/cityscapes_b.py", line 69, in mix
    name = random.sample(self.label_to_file[class_idx], 1)
  File "/home/tianyuntong/anaconda3/envs/dtst/lib/python3.6/random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

**Comment by tianyuntong1020** [comment]
> Hi, could you provide the full print log? In cityscapes_b.py, if the predicted probability of a class is 0, it will not be sampled.

Traceback (most recent call last):
------------------------city balance sample-----------------------------
  File "train_TCR_DTU.py", line 948, in <module>
    main()
  File "train_TCR_DTU.py", line 941, in main
    fea, cls = train(cfg, args.local_rank, args.distributed)
  File "train_TCR_DTU.py", line 414, in train
    for i, (tgt_input, y, names, tgt_trans_param, tgt_img_full, mix_label) in enumerate(tgt_train_loader):
  File "/home/tianyuntong/anaconda3/envs/dtst/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/tianyuntong/anaconda3/envs/dtst/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/tianyuntong/anaconda3/envs/dtst/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tianyuntong/anaconda3/envs/dtst/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/tianyuntong/project/DT-ST-main/core/datasets/cityscapes_b.py", line 377, in __getitem__
    trans_image, mix_label = self.mixer.mix(trans_image, self.mix_classes, self.mix_p)
  File "/home/tianyuntong/project/DT-ST-main/core/datasets/cityscapes_b.py", line 69, in mix
    name = random.sample(self.label_to_file[class_idx], 1)
  File "/home/tianyuntong/anaconda3/envs/dtst/lib/python3.6/random.py", line 320, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

**Comment by DZhaoXd** [comment]
It seems that it is indeed caused by the source model not predicting a certain class. We'll update the code later. Thanks for your feedback.

**Comment by DZhaoXd** [comment]
Hello, I have updated the cityscapes_b.py. Currently, the TCR will no longer select non-existing classes as paste objects. Thanks for your prompt.  If you have another question, feel free to contact me.

**Comment by tianyuntong1020** [comment]
> Hello, I have updated the cityscapes_b.py. Currently, the TCR will no longer select non-existing classes as paste objects. Thanks for your prompt. If you have another question, feel free to contact me.

Thank you so much. If I have any further questions, I'll come back for your help.

**Comment by tianyuntong1020** [comment]
> Hello, I have updated the cityscapes_b.py. Currently, the TCR will no longer select non-existing classes as paste objects. Thanks for your prompt. If you have another question, feel free to contact me.
Hello, when the predicted probability of a certain category is 0, if the object of this category is no longer paste, will the performance of this category be affected by this manner and difficult to improve performance?

**Comment by tianyuntong1020** [comment]
> Hello, I have updated the cityscapes_b.py. Currently, the TCR will no longer select non-existing classes as paste objects. Thanks for your prompt. If you have another question, feel free to contact me.

Hello, when the predicted probability of a certain category is 0, if the object of this category is no longer paste, will the performance of this category be affected by this manner and difficult to improve performance?

**Comment by DZhaoXd** [comment]
Yes, I think so. If possible, you can contact me directly using WeChat: zd1564421854.

**Comment by tianyuntong1020** [comment]
> Yes, I think so. If possible, you can contact me directly using WeChat: zd1564421854
